### ISSUE TITLE
When a DateTime field uses a custom dateformat, a value given to the controller isn't formatted accordingly

### ISSUE THREAD

**Issue by PureTryOut** [Iconica-Development/flutter_form_wizard#9]
For example:

```dart
FlutterFormInputDateTimeController(
      id: "Date",
      dateTimeType: FlutterFormDateTimeType.date,
      dateFormat: DateFormat('dd-MM-yy'),
      checkPageTitle: (dynamic date) => "Date: $date",
      onChanged: (String? value) => someFunction(value),
      value: "2022-10-25 08:32:45.544533",
    );
```

This will result in a form field with the value printed as is (2022-10-25 08:32:45.544533) rather than in the given `dd-MM-yy` format. This means I have to manually format the date myself before passing it to the controller which is a bit annoying.
Also it would be great if instead of a string I could just pass the DateTime object itself.

**Comment by Gorter-dev** [comment]
https://github.com/Iconica-Development/flutter_form_wizard/pull/30
